services:
  postgres:
    container_name: swift_code_app
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: swift
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped