services:
  postgres:
    container_name: swift-code-app
    image: postgres:17.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: swift
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped