server:
    port: 8080

cors:
    allowed-origins: ${CORS_ORIGINS:"*"}
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"

spring:
    application:
        name: swift-codes-app
    datasource:
        url: jdbc:postgresql://localhost:5432/swift
        username: admin
        password: admin
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true

